//domain
http://localhost:4000


//this headers will be set to every request automaticaly
Content-Type: application/json
Authorization: Bearer [your access token]

--
--
#get customer profile
GET /api/customer/profile

--
# add a address
POST /api/customer/address
{
"street":"new road",
"postalCode":"1216",
"city":"dhaka",
"country":"bangladesh"
}
--
#delete a address
DELETE /api/customer/address/638c86397a28511f54302496
--
#get all address
GET /api/customer/address
--
#change name
PUT /api/customer/profile/change-name
{
  "name":"Name changed"
}
--
#change phone number
PUT /api/customer/phone
{
  "phone":"12345678"
}

--
#get your cart 
GET /api/customer/cart
--
#add to cart 
POST /api/customer/cart/
{
  "product":"638c8d41a8232da6031ba8dd",
  "quantity":"3"
}
--
#remove to cart
DELETE /api/customer/cart/638c8d41a8232da6031ba8dd

--
#get wishlist 
GET /api/customer/wishlist

--
#add to wishlist
POST /api/customer/wishlist/638c8d41a8232da6031ba8dd
--
#remove to wishlist
DELETE /api/customer/wishlist/638c8d41a8232da6031ba8dd

--
#get pending orders
GET /api/customer/orders

--
#get purchase history
GET /api/customer/purchase-history
