//domain
http://localhost:4000


//this headers will be set to every request automaticaly
Content-Type: application/json
Authorization: Bearer [your access token]

--
--
#create order
POST /api/order
{

"products":[
{"productId":"638dd20ce9fc65bdfa588d3b", "quantity":300}
],
"address":"63889758b151310ef425932b"
}
--
//cancel order
DELETE /api/order/638dc2e4c7aafa9e514c6dfd  
