//domain
http://localhost:4000

//this headers will be set to every request automaticaly
Content-Type: application/json
Authorization: Bearer [your access token]

--
--
#get products 
GET /api/products

--
#search products by name
GET /api/products/Watermelon

--
#search products by category
GET /api/products/category/Fruits

--
#find selected products 
POST /api/products/ids
{
"ids":["638dd20ce9fc65bdfa588d3b"]

}
--
#review a product 
POST /api/products/reviews/638dd20ce9fc65bdfa588d3b
{
"rating":"5",
"text":"the Watermelon is very fresh .I totally loved it."

}
--
//update your review
PUT /api/products/reviews/638dd20ce9fc65bdfa588d3b
{
"rating":"1",
"text":"Very bad Watermelon."

}
--
#delete review
DELETE /api/products/reviews/638dd20ce9fc65bdfa588d3b

--
