//domain
http://localhost:4000

//this headers will be set to every request automaticaly
Content-Type: application/json
Authorization: Bearer [your access token]

--
--
#create a product
POST /api/products
{
  "name":"Watermelon",
  "price":122,
  "description":"Great quality of Watermelon",
  "category":"Fruits",
  "unit":1,
  "availableUnits":200,
  "supplier":"Muttaqin muhammad"
  
}

--
#update a product
PUT /api/products/638dcc7c83c3d8b50ac98b58
{
"name":"Product updated"
}
--
#delete a product
DELETE /api/products/638dcc7c83c3d8b50ac98b58

--
#complete a order
PUT /api/orders/complete/638f27780229c023511edb53 

--
#get the stock status
GET /api/products/stock/status

--
#get monthly income
GET /api/orders/monthly-income
--
#get all orders
GET /api/orders/pending-orders

--
#generate discount token
POST /api/token/discount-token
{
"name":"winter special discount",
"code":"WIN332",
"discountPercentage":30
}

--
#get discount token
POST /api/discount-token
{
  "code":"WIN332"
}
--
